export const actions = {
    GET_MOVIE_BANNER: "GET_MOVIE_BANNER",
    GET_MOVIE_UPCOMING: "GET_MOVIE_UPCOMING",
    GET_MOVIE_NOW_SHOWING: "GET_MOVIE_NOW_SHOWING",
    GET_MOVIE_POPULAR: "GET_MOVIE_POPULAR",
    GET_MOVIE_DETAIL: "GET_MOVIE_DETAIL",
    GET_MOVIE_TRAILER: "GET_MOVIE_TRAILER",
    GET_MOVIE_TOP_RATED: "GET_MOVIE_TOP_RATED",
    GET_MOVIE_GENRES: "GET_MOVIE_GENRES"
}